//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos
    {
        public int Id { get; set; }
       
        public string Marca { get; set; }
   
        public string Serial { get; set; }
      
        public string Observaciones { get; set; }
      
        public Nullable<int> idEstado { get; set; }
    
        public virtual estado_Activo estado_Activo { get; set; }
    }
}
